blank_issues_enabled: true
template_selection_enabled: true
templates:
  - name: Feature Request
    path: feature_request.md
    description: Submit a new feature implementation
  
  - name: Bug Fix
    path: bug_fix.md
    description: Submit a bug fix
  
  - name: Documentation Update
    path: documentation_update.md
    description: Update project documentation
    
  - name: Task Completion
    path: task_completion.md
    description: Submit completed task work
