blank_issues_enabled: false
contact_links:
  - name: Discussion
    url: https://github.com/orgs/turboline-ai/discussions
    about: Check our documentation before creating an issue
  - name: Security Policy
    url: https://github.com/Turboline/security/security/policy
    about: Please see our security policy before creating an issue

templates:
  - name: Bug Report
    about: Report a bug or error
    filename: bug_report.md
    labels: [bug]
    
  - name: Feature Request
    about: Suggest a new feature
    filename: feature_request.md
    labels: [enhancement]
    
  - name: Task Tracking
    about: Create a new task
    filename: task_completion.md
    labels: [task]
    
  - name: Custom Issue
    about: For other types of issues
    filename: custom_template.md
    labels: [custom]
